version: '2'

services:
  peer2.org1.example.com:
    container_name: peer3.org1.example.com
    image: hyperledger/fabric-peer:$ARCH-1.0.3
    environment:
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer3.org1.example.com
      - CORE_PEER_ADDRESS=peer3.org1.example.com:7051
      # - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=composer_default
      # - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=asclepeion-net
      - CORE_PEER_LOCALMSPID=Org1MSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-defaultchain=false
    ports:
      - 7051:7051
      - 7053:7053
    external_links:
      - orderer.example.com:orderer.example.com
      - peer0.org1.example.com:peer0.org1.example.com
      - peer2.org1.example.com:peer2.org1.example.com
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto_material/crypto-config/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/msp/:/etc/hyperledger/fabric/msp
        - ./crypto_material/channel-artifacts/:/etc/hyperledger/configtx
        - ./crypto_material/crypto-config/:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/

    depends_on:
      - couchdb3

  couchdb3:
    container_name: couchdb3
    image: hyperledger/fabric-couchdb:$ARCH-1.0.3
    ports:
      - 5984:5984
    environment:
      - COUCHDB_PASSWORD=
      - COUCHDB_USER=
      - DB_URL=http://localhost:5984/member_db
